nameOverride: ""
fullnameOverride: ""

replicas: 2

image:
  repository: registry.boo.eth0.work/library/patroni
  pullPolicy: IfNotPresent
  tag: null

storage:
  pgdata:
    class: ""
    accessMode: ReadWriteOnce
    size: 1Gi
  repository:
    class: ""
    accessMode: ReadWriteOnce
    size: 5Gi

distributePods: "hard"

nodeSelector: {}

imagePullSecrets: []

resources:
  patroni: {}

settings:
  users:
    super: postgres
    replication: replicator

  backup:
    schedule:
      incremental:  "14 */3 * * *"
      full:  "27 12 * * 7"

  bootstrap:
    max_connections:
    max_locks_per_transaction:
    max_worker_processes:
    wal_keep_size:
    max_prepared_transactions:
    wal_level:
    track_commit_timestamp:
    max_wal_senders:
    max_replication_slots:
    wal_log_hints:

  pgbackrest.conf: |
    [global]
    repo1-path=/var/lib/pgbackrest

    [main]
    pg1-path=/var/lib/postgresql/data

  postgresql.conf: ""
