apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: repository
  namespace: patroni
spec:
  storageClassName: nfs-storage
  resources:
    requests:
      storage: 50Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
